"""add instance health snapshot column

Revision ID: 380f17bd133f
Revises: 3e12e0c78a08
Create Date: 2026-07-29 20:04:43.580068
"""

from __future__ import annotations

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "380f17bd133f"
down_revision = "3e12e0c78a08"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default added by hand: NOT NULL with no default would reject
    # this ALTER TABLE outright against any pre-existing instances rows.
    op.add_column(
        "instances",
        sa.Column(
            "health",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default="{}",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("instances", "health")
    # ### end Alembic commands ###
