"""add instances table

Revision ID: 3e12e0c78a08
Revises: 0001
Create Date: 2026-07-27 18:38:40.339968
"""

from __future__ import annotations

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "3e12e0c78a08"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "instances",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("base_url", sa.String(length=255), nullable=False),
        sa.Column("enabled_services", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("health_status", sa.String(length=32), nullable=False),
        sa.Column("cms_url", sa.String(length=255), nullable=True),
        sa.Column("pm_url", sa.String(length=255), nullable=True),
        sa.Column("pim_url", sa.String(length=255), nullable=True),
        sa.Column("erp_url", sa.String(length=255), nullable=True),
        sa.Column("ai_url", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("instances")
    # ### end Alembic commands ###
